# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CloneInsta' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloneInsta
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'SnapKit', '~> 5'
  pod 'SwiftyJSON', '~> 5'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SwiftyUserDefaults', '~> 4.0'
end
